version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
  - package-ecosystem: npm
    directory: /web
    schedule: {interval: weekly}
  - package-ecosystem: nuget
    directory: /services/api
    schedule: {interval: weekly}
  - package-ecosystem: maven
    directory: /services/worker
    schedule: {interval: weekly}
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule: {interval: weekly}
